export const languages = [
    { code: 'zh', name: '中文' },
    { code: 'en', name: '英语' },
    { code: 'ja', name: '日语' },
    { code: 'ko', name: '韩语' },
    { code: 'fr', name: '法语' },
    { code: 'de', name: '德语' },
    { code: 'es', name: '西班牙语' },
    { code: 'it', name: '意大利语' },
    { code: 'ru', name: '俄语' },
    { code: 'ar', name: '阿拉伯语' },
    { code: 'pl', name: '波兰语' },
    { code: 'th', name: '泰语' },
    { code: 'pt', name: '葡萄牙语' },
    { code: 'el', name: '希腊语' },
    { code: 'nl', name: '荷兰语' },
    { code: 'hu', name: '匈牙利语' },
    { code: 'cs', name: '捷克语' },
    { code: 'ro', name: '罗马尼亚语' },
    { code: 'sv', name: '瑞典语' },
    { code: 'vi', name: '越南语' },
    { code: 'tr', name: '土耳其语' },
    { code: 'hi', name: '印地语' },
    { code: 'id', name: '印尼语' },
    { code: 'ms', name: '马来语' },
    { code: 'no', name: '挪威语' },
    { code: 'he', name: '希伯来语' },
    { code: 'fa', name: '波斯语' },
    { code: 'tl', name: '菲律宾语' },
    { code: 'bn', name: '孟加拉语' },
    { code: 'bul', name: '保加利亚语' },
    { code: 'est', name: '爱沙尼亚语' },
    { code: 'dan', name: '丹麦语' },
    { code: 'fin', name: '芬兰语' },
    { code: 'slo', name: '斯洛文尼亚语' },
    { code: 'yue', name: '粤语' },
    { code: 'wyw', name: '文言文' },
    { code: 'cht', name: '繁体中文' },
    { code: 'sr', name: '塞尔维亚语' },
    { code: 'uk', name: '乌克兰语' }
];

// 添加 API 语言代码映射，保持前端语言代码不变
export const apiLanguageMap: { [key: string]: string } = {
    'zh': 'zh',
    'en': 'en',
    'ja': 'jp',
    'ko': 'kor',
    'fr': 'fra',
    'es': 'spa',
    'th': 'th',
    'ar': 'ara',
    'ru': 'ru',
    'de': 'de',
    'it': 'it',
    'pl': 'pl',
    'pt': 'pt',
    'el': 'el',
    'nl': 'nl',
    'hu': 'hu',
    'cs': 'cs',
    'ro': 'rom',
    'sv': 'swe',
    'vi': 'vie',
    'tr': 'tr',
    'hi': 'hi',
    'id': 'id',
    'ms': 'ms',
    'no': 'no',
    'he': 'he',
    'fa': 'fa',
    'tl': 'tl',
    'bn': 'bn',
    'bul': 'bul',
    'est': 'est',
    'dan': 'dan',
    'fin': 'fin',
    'slo': 'slo',
    'yue': 'yue',
    'wyw': 'wyw',
    'cht': 'cht',
    'sr': 'sr',
    'uk': 'uk'
};

export const languageMap: { [key: string]: string } = {
    'zh': '中文',
    'en': '英语',
    'ja': '日语',
    'ko': '韩语',
    'fr': '法语',
    'de': '德语',
    'es': '西班牙语',
    'it': '意大利语',
    'ru': '俄语',
    'ar': '阿拉伯语',
    'pl': '波兰语',
    'th': '泰语',
    'pt': '葡萄牙语',
    'el': '希腊语',
    'nl': '荷兰语',
    'hu': '匈牙利语',
    'cs': '捷克语',
    'ro': '罗马尼亚语',
    'sv': '瑞典语',
    'vi': '越南语',
    'tr': '土耳其语',
    'hi': '印地语',
    'id': '印尼语',
    'ms': '马来语',
    'no': '挪威语',
    'he': '希伯来语',
    'fa': '波斯语',
    'tl': '菲律宾语',
    'bn': '孟加拉语',
    'bul': '保加利亚语',
    'est': '爱沙尼亚语',
    'dan': '丹麦语',
    'fin': '芬兰语',
    'slo': '斯洛文尼亚语',
    'yue': '粤语',
    'wyw': '文言文',
    'cht': '繁体中文',
    'sr': '塞尔维亚语',
    'uk': '乌克兰语'
};

export const languagePrompts: { [key: string]: string } = {
    'zh': '请使用中文回答',
    'en': 'Please respond in English only',
    'ja': '日本語で回答してください',
    'ko': '한국어로 답변해 주세요',
    'fr': 'Veuillez répondre en français uniquement',
    'de': 'Bitte antworten Sie nur auf Deutsch',
    'es': 'Por favor, responda solo en español',
    'it': 'Si prega di rispondere solo in italiano',
    'ru': 'Пожалуйста, отвечайте только на русском языке',
    'ar': 'الرجاء الرد باللغة العربية فقط',
    'pl': 'Proszę odpowiadać tylko w języku polskim',
    'th': 'กรุณาตอบเป็นภาษาไทยเท่านั้น',
    'pt': 'Por favor, responda apenas em português',
    'el': 'Παρακαλώ απαντήστε μόνο στα ελληνικά',
    'nl': 'Antwoord alstublieft alleen in het Nederlands',
    'hu': 'Kérjük, válaszoljon csak magyarul',
    'cs': 'Prosím, odpovězte pouze v češtině',
    'ro': 'Vă rugăm să răspundeți doar în română',
    'sv': 'Vänligen svara endast på svenska',
    'vi': 'Vui lòng chỉ trả lời bằng tiếng Việt',
    'tr': 'Lütfen sadece Türkçe yanıt verin',
    'hi': 'कृपया केवल हिंदी में उत्तर दें',
    'id': 'Silakan jawab hanya dalam bahasa Indonesia',
    'ms': 'Sila jawab dalam bahasa Melayu sahaja',
    'no': 'Vennligst svar kun på norsk',
    'he': 'אנא ענה רק בעברית',
    'fa': 'لطفاً فقط به فارسی پاسخ دهید',
    'tl': 'Mangyaring sumagot lamang sa Tagalog',
    'bn': 'অনুগ্রহ করে শুধুমাত্র বাংলায় উত্তর দিন',
    'bul': 'Моля, отговорете само на български',
    'est': 'Palun vastake ainult eesti keeles',
    'dan': 'Svar venligst kun på dansk',
    'fin': 'Vastaa vain suomeksi',
    'slo': 'Prosim, odgovorite samo v slovenščini',
    'yue': '請用廣東話回答',
    'wyw': '請用文言文回答',
    'cht': '請用繁體中文回答',
    'sr': 'Молимо одговорите само на српском',
    'uk': 'Будь ласка, відповідайте тільки українською'
};
